### ISSUE TITLE
run this just once!?

### ISSUE THREAD

**Issue by MohsenShafiee** [sacot41/SCViewPager#1]
thanks for the library
I use it as my main activity! and start another activity in the last page of pager!
would you please tell me how to run this just once when app is recently installed?! and hide it next runs!?

**Comment by sacot41** [comment]
I recommend to not make this in your mainActivity. Use your mainActivity like you do normally for your app (what you want to do in your "next" activity).
In onCreate of mainActivity, check for a boolean in sharedpreference. If boolean doesn't existe, it means that is first time application is open. Save this value to true, and open, for example, "DemoActivity". 

This is a example to check if it's first time app is opening : http://stackoverflow.com/questions/4636141/determine-if-android-app-is-the-first-time-used

"DemoActivity" implement demo of your app with this library. 
You can listing to last page with "ViewPager.OnPageChangeListener" on viewpage, and check for last page to close your DemoActivity and go back to your mainActivity. 

I going to add a function in util class to easy check if it's first time the app is open.

**Comment by MohsenShafiee** [comment]
thanks :)
but it would be much better if you implement this in your example app... I mean that demo activity and the way it comes back to main activity...
