### ISSUE TITLE
there will be huge offset when moving rapidly

### ISSUE THREAD

**Issue by weizai** [sacot41/SCViewPager#3]
there will be Bugs when moving rapidly

**Comment by sacot41** [comment]
It's like scrollview skip some callback. I going to check this.

**Comment by Nightonke** [comment]
It still has bugs when swiping quietly.

**Comment by q8533557** [comment]
Is there a good solution?

**Comment by Nightonke** [comment]
Maybe we can limit the swiping speed?

**Comment by sacot41** [comment]
Hum, simple, a little bit hacky, but if it works , it's not stupid. I going to test that ASAP. Do you known a simple solution to limit de speed of a scrollview (aka viewPager),  ?

**Comment by Nightonke** [comment]
Hey, I have solve this problem. And also I create a new library which has more animations. You can found it here: https://github.com/Nightonke/WoWoViewPager

**Comment by sacot41** [comment]
Indeed, you seem to have fixed the problem and have added a lot of animation. On the other hand, 
if you use the code and concepts of someone, at least, indicates the source in your readme....

**Comment by Nightonke** [comment]
I'm sorry about that. I have add the indication in my readme.

**Comment by sacot41** [comment]
Thank you. I add a link to your library in the readme of this projet.
